name: suriota_mobile_gateway
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  iconify_flutter: ^0.0.5
  gap: ^3.0.1
  multi_dropdown: ^3.0.1
  dropdown_search: ^5.0.5
  flutter_screenutil: ^5.9.3
  path_provider_foundation: ^2.4.0
  get: ^4.6.6
  permission_handler: ^11.3.1
  get_storage: ^2.1.1
  flutter_blue_plus: ^1.35.3
  flutter_launcher_icons: ^0.14.3
  provider: ^6.1.4
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon_suriota.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/